# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20160324_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, default='', max_length=1024),
        ),
    ]
