# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
